"""Remove driver_id from locations table

Revision ID: e0c218a230e3
Revises: 6a23491ec844
Create Date: 2026-05-23 21:19:58.958532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c218a230e3'
down_revision: Union[str, Sequence[str], None] = '6a23491ec844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('locations_driver_id_fkey'), 'locations', type_='foreignkey')
    op.drop_column('locations', 'driver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('locations_driver_id_fkey'), 'locations', 'drivers', ['driver_id'], ['id'])
    # ### end Alembic commands ###
